---
- name: Set Spectacle Shortcut
  ansible.builtin.command: kwriteconfig5 --file kglobalshortcutsrc --group spectacle --key RectangularRegionScreenShot "Meta+Shift+S,Meta+Shift+Print,Capture Rectangular Region"
  ignore_errors: yes

- name: Restart Plasma global accel service
  ansible.builtin.shell: systemctl --user restart plasma-kglobalaccel.service
  args:
    executable: /bin/bash
  ignore_errors: yes
