---
- name: Disable Ubuntu default IBus injection for Wayland compatibility
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.xinputrc"
    content: |
      run_im none
    mode: '0644'

- name: Pre-answer display manager prompt for SDDM
  become: yes
  ansible.builtin.debconf:
    name: sddm
    question: shared/default-x-display-manager
    value: sddm
    vtype: select

- name: Install KDE standard without prompts
  become: yes
  ansible.builtin.apt:
    name: kde-standard
    state: present
    update_cache: yes

- name: Install KDE Plasma Wayland and specific tools
  become: yes
  ansible.builtin.apt:
    name:
      - plasma-workspace-wayland
      - systemsettings
      - plasma-desktop
      - kde-config-sddm
      - kde-config-gtk-style
      - kde-config-gtk-style-preview
      - plasma-look-and-feel-org.kde.breeze.desktop
      - qt5-style-kvantum
      - qt6-style-kvantum
      - sddm-theme-breeze
      - language-pack-kde-pl
    state: present
    update_cache: yes

- name: Set SDDM input method config
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/sddm.conf
    create: yes
    block: |
      [General]
      InputMethod=
    mode: '0644'

- name: Reconfigure SDDM
  become: yes
  ansible.builtin.command: dpkg-reconfigure -f noninteractive sddm

- name: Fix SDDM directory ownership
  become: yes
  ansible.builtin.file:
    path: /var/lib/sddm
    owner: sddm
    group: sddm
    recurse: yes
