#!/usr/bin/env python3
"""Generate the three vendor package manifests from this repository's own single source.

    python3 setup/manifests/generate.py            write the three files
    python3 setup/manifests/generate.py --check    write nothing, exit 1 if any file is out of date

The manifests let someone bootstrap a machine with the vendor's own tooling instead of running the
whole playbook. They are generated rather than written by hand, because a hand-written copy of a
package list is a second source of truth, and this repository has already paid for that mistake more
than once.

What comes from where:

    group_vars/all.yaml overlaid by group_vars/<os>.yaml    which applications are wanted
    vars/Windows.yaml and vars/Darwin.yaml                  what each one is called per manager
    setup/pinned_values, through its own reader             versions, see the note on pinning below

Nothing here parses the pinned values file directly. That rule has one owner, setup/pinned_values,
and e2e/tier1/pinned_values.sh fails the gate if a second parser appears.

On pinning. Only two of the three formats can carry a version at all, and this repository pins a
version for very few of the applications they cover, so the manifests deliberately do not pin. Three
reasons, in order of weight. The playbook does not pin either: the Windows installer runs
`winget install --exact --id <id>` with no version argument, so pinning here would be new behaviour
rather than a translation of existing behaviour. A version that does not exist in the target feed is
a hard failure rather than a fallback, and two of the pins that would apply are in the wrong shape
for their feed already, `v1.38.1` for minikube and a Python patch release that the winget package's
own versioning does not follow. And Homebrew has said it will never support pinning, so a Brewfile
could not agree with the other two anyway. If pinning is wanted later, it needs a check that each
version really exists in the feed, which is a network call this generator does not make.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GROUP_VARS = REPO / "setup" / "ansible" / "group_vars"
VARS = REPO / "setup" / "ansible" / "vars"
HERE = Path(__file__).resolve().parent

TOGGLE = re.compile(r"^(install_[a-z0-9_]+):\s*(true|false)\s*(?:#.*)?$", re.MULTILINE)
MAPPING = re.compile(
    r'^  (?P<key>[a-z0-9_]+):\s*\{\s*manager:\s*"(?P<manager>[a-z_]+)"\s*,\s*'
    r'package:\s*"(?P<package>[^"]*)"(?P<rest>[^}]*)\}',
    re.MULTILINE,
)
SOURCE = re.compile(r'source:\s*"([^"]*)"')

GENERATED_BY = "setup/manifests/generate.py"


def strip_comments(text: str) -> str:
    """Remove trailing comments so a commented-out example never reads as a real entry."""
    return "\n".join(re.sub(r"\s+#.*$", "", line) for line in text.splitlines())


def toggles(*names: str) -> dict[str, bool]:
    """Toggle values, per-OS file layered over the cross-platform one, the wizard's own precedence."""
    resolved: dict[str, bool] = {}
    for name in names:
        text = strip_comments((GROUP_VARS / f"{name}.yaml").read_text(encoding="utf-8"))
        for key, value in TOGGLE.findall(text):
            resolved.setdefault(key[len("install_") :], value == "true")
    return resolved


def mappings(family: str) -> list[dict[str, str]]:
    """Every application mapped for one family, in file order."""
    text = (VARS / f"{family}.yaml").read_text(encoding="utf-8")
    entries = []
    for match in MAPPING.finditer(text):
        source = SOURCE.search(match.group("rest") or "")
        entries.append(
            {
                "key": match.group("key"),
                "manager": match.group("manager"),
                "package": match.group("package"),
                "source": source.group(1) if source else "",
            }
        )
    return entries


def wanted(family: str, *toggle_files: str) -> list[dict[str, str]]:
    """The mapped applications a default run of that platform would install, sorted by name."""
    on = toggles(*toggle_files)
    chosen = [entry for entry in mappings(family) if on.get(entry["key"], False)]
    return sorted(chosen, key=lambda entry: entry["key"])


def header(lines: list[str], comment: str = "#") -> str:
    prefix = f"{comment} "
    return "\n".join(prefix + line if line else comment for line in lines)


def brewfile() -> str:
    chosen = wanted("Darwin", "macos", "all")
    formulae = [entry for entry in chosen if entry["manager"] == "brew"]
    casks = [entry for entry in chosen if entry["manager"] == "brew_cask"]

    lines = header(
        [
            f"Generated by {GENERATED_BY}. Do not edit by hand.",
            "",
            "Every application the playbook would install on macOS with the toggles as they ship,",
            "expressed as a Brewfile so a Mac can be brought up with Homebrew alone.",
            "",
            f"{len(formulae)} formulae and {len(casks)} casks. Install with:",
            "",
            "    brew bundle install --file setup/manifests/Brewfile",
            "",
            "brew bundle needs no tap: it was merged into Homebrew itself in 4.5.0.",
            "",
            "What this file cannot express, and the playbook does. Homebrew has no version pinning and",
            "has said it will not, so nothing here is pinned. The applications installed from a vendor",
            "disk image rather than from Homebrew are absent, and so is everything the sdk_manager and",
            "ai_tools roles install, which is every language runtime and every command line tool that",
            "arrives through SDKMAN, Pyenv, NVM, FVM, the Android SDK or npm. This is a package list,",
            "the playbook is a configuration tool.",
        ]
    ).splitlines()

    body = ["", "# Command line tools"]
    body += [f'brew "{entry["package"]}"' for entry in formulae]
    body += ["", "# Applications"]
    body += [f'cask "{entry["package"]}"' for entry in casks]
    return "\n".join(lines + body) + "\n"


def packages_config() -> str:
    chosen = [entry for entry in wanted("Windows", "windows", "all") if entry["manager"] == "choco"]

    lines = [
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
        "<!--",
        f"  Generated by {GENERATED_BY}. Do not edit by hand.",
        "",
        "  The Chocolatey half of the Windows software set. Only the applications winget cannot",
        f"  serve are here, which is {len(chosen)} of them, and each one's reason is a comment in",
        "  setup/ansible/vars/Windows.yaml beside the mapping. The other 80-odd are in",
        "  setup/manifests/configuration.winget.",
        "",
        "  Install from an administrative shell with:",
        "",
        "      choco install setup\\manifests\\packages.config -y --no-progress",
        "",
        "  No version attribute is emitted, because the playbook does not pin one either. See the",
        "  note at the top of the generator for why.",
        "-->",
        "<packages>",
    ]
    lines += [f'  <package id="{entry["package"]}" />' for entry in chosen]
    lines.append("</packages>")
    return "\n".join(lines) + "\n"


def winget_configuration() -> str:
    chosen = [entry for entry in wanted("Windows", "windows", "all") if entry["manager"] == "winget"]
    store = [entry for entry in chosen if entry["source"] == "msstore"]
    community = [entry for entry in chosen if entry["source"] != "msstore"]

    lines = [
        "# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2",
        "#",
        f"# Generated by {GENERATED_BY}. Do not edit by hand.",
        "#",
        "# The winget half of the Windows software set, as a winget configuration file. Schema 0.2,",
        "# which is the Desired State Configuration version 2 shape and the one Microsoft documents",
        "# and ships in its own repository. The 0.3 alias points at a different document format and",
        "# needs metadata.winget.processor set to dscv3, which Microsoft does not document at all.",
        "#",
        "# Apply it from an elevated shell with:",
        "#",
        "#     winget configure -f setup\\manifests\\configuration.winget --accept-configuration-agreements --disable-interactivity",
        "#",
        "# Elevation is per resource, and one User Account Control dialog appears at the start unless",
        "# the shell is already elevated. No flag suppresses that dialog, so an already-elevated",
        "# session is the only unattended route.",
        "#",
        f"# {len(community)} packages from the winget community repository and {len(store)} from the",
        "# Microsoft Store. The Store entries are product identifiers rather than manifests, they need",
        "# the Store present and its agreement accepted, and they are the least portable thing here.",
        "#",
        "# Not expressible: the Chocolatey applications, which have no first-party winget resource and",
        "# live in setup/manifests/packages.config, and the two vendor executables the playbook",
        "# downloads directly. No version is pinned, see the generator's own note for why.",
        "properties:",
        "  resources:",
    ]

    for entry in community + store:
        lines += [
            "    - resource: Microsoft.WinGet.DSC/WinGetPackage",
            f"      id: {entry['key']}",
            "      directives:",
            f"        description: Install {entry['key']} ({entry['package']})",
            "        allowPrerelease: false",
            "      settings:",
            f"        id: {entry['package']}",
            f"        source: {entry['source'] or 'winget'}",
        ]

    lines.append("  configurationVersion: 0.2.0")
    return "\n".join(lines) + "\n"


MANIFESTS = {
    "Brewfile": brewfile,
    "packages.config": packages_config,
    "configuration.winget": winget_configuration,
}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="write nothing, report what is out of date")
    args = parser.parse_args(argv)

    stale = []
    for name, render in MANIFESTS.items():
        path = HERE / name
        rendered = render()
        if args.check:
            # Bytes rather than text, on purpose. Path.read_text and Path.write_text only accept
            # a newline argument from Python 3.13, and this has to run wherever the shell
            # adapter's interpreter search lands, which is 3.11 upward. Measured: Git Bash here
            # has 3.13.15 and WSL has 3.12.3, so the text form worked in one shell and crashed
            # in the other. Bytes also keep the comparison honest, since the text form would
            # translate line endings on the way in and out and a file written on Windows would
            # then compare unequal to the same file read on Linux.
            current = path.read_bytes() if path.exists() else None
            if current != rendered.encode("utf-8"):
                stale.append(name)
        else:
            path.write_bytes(rendered.encode("utf-8"))
            print(f"wrote {path.relative_to(REPO)} ({len(rendered.splitlines())} lines)")

    if args.check:
        if stale:
            sys.stderr.write(
                "these manifests no longer match the toggles and mappings they are generated from: "
                + ", ".join(stale)
                + f"\nregenerate with: python3 {GENERATED_BY}\n"
            )
            return 1
        print(f"all {len(MANIFESTS)} manifests are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
