---
- name: Install ZSH and curl (Debian)
  ansible.builtin.apt:
    name:
      - zsh
      - curl
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install ZSH and curl (Fedora)
  ansible.builtin.dnf:
    name:
      - zsh
      - curl
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install ZSH and curl (Archlinux)
  community.general.pacman:
    name:
      - zsh
      - curl
    state: present
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Install ZSH (macOS)
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_os_family == 'Darwin'

- name: Find ZSH path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Change user shell to ZSH
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes
