---
- name: Install Oh-My-Zsh
  ansible.builtin.shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  become: no

- name: Copy ZSH configuration files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  loop:
    - ".p10k.zsh"
    - ".zshrc.pre-oh-my-zsh"
    - ".zshrc"
  become: no
