---
- name: Add Ledger udev rules
  ansible.builtin.shell: wget -q -O - "https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh" | bash
  become: yes
  changed_when: false
  when: install_ledger_live | bool

- name: Add Trezor udev rules (Debian)
  ansible.builtin.apt:
    deb: "https://data.trezor.io/udev/trezor-udev_2_all.deb"
  become: yes
  when: install_trezor_suite | bool and ansible_facts['os_family'] == 'Debian'

- name: Add Trezor udev rules (RedHat)
  ansible.builtin.get_url:
    url: "https://data.trezor.io/udev/51-trezor.rules"
    dest: /etc/udev/rules.d/51-trezor.rules
    mode: '0644'
  become: yes
  when: install_trezor_suite | bool and ansible_facts['os_family'] == 'RedHat'

- name: Reload udev rules (RedHat)
  ansible.builtin.command: udevadm control --reload-rules
  become: yes
  changed_when: false
  when: install_trezor_suite | bool and ansible_facts['os_family'] == 'RedHat'

- name: Add Trezor udev rules (Archlinux)
  become: yes
  kewlfft.aur.aur:
    name: trezor-udev
    use: yay
    state: present
  when: install_trezor_suite | bool and ansible_facts['os_family'] == 'Archlinux'
