---
- name: Install cmake
  ansible.builtin.apt:
    name: cmake
    state: present
  become: yes

- name: Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: Install kubectl binary
  become: yes
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Run Helm installation script
  become: yes
  ansible.builtin.command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Download FVM installation script
  ansible.builtin.get_url:
    url: https://fvm.app/install.sh
    dest: /tmp/fvm_install.sh
    mode: '0700'

- name: Install FVM for Flutter Version Management
  become: yes
  ansible.builtin.command: /tmp/fvm_install.sh
  args:
    creates: /usr/local/bin/fvm

- name: Download JetBrains Toolbox
  ansible.builtin.get_url:
    url: "https://data.services.jetbrains.com/products/download?code=TBA&platform=linux"
    dest: "/tmp/jetbrains-toolbox.tar.gz"

- name: Create JetBrains directory
  become: yes
  ansible.builtin.file:
    path: "/opt/jetbrains-toolbox"
    state: directory

- name: Extract JetBrains Toolbox
  become: yes
  ansible.builtin.unarchive:
    src: "/tmp/jetbrains-toolbox.tar.gz"
    dest: "/opt/jetbrains-toolbox"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Symlink JetBrains Toolbox to path
  become: yes
  ansible.builtin.file:
    src: "/opt/jetbrains-toolbox/jetbrains-toolbox"
    dest: "/usr/local/bin/jetbrains-toolbox"
    state: link
