---
- name: Install Flatpak and KDE integration
  become: yes
  ansible.builtin.apt:
    name:
      - flatpak
      - plasma-discover-backend-flatpak
    state: present
  when: setup_kde_plasma | bool

- name: Enable Flatpak
  ansible.builtin.apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present
  become: yes
  when: not setup_kde_plasma | bool

- name: Add Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  become: yes

- name: Install Flatpak Applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop:
    - com.github.tchx84.Flatseal
    - org.angryip.ipscan
    - us.zoom.Zoom
    - io.github.shiftey.Desktop
    - org.onlyoffice.desktopeditors
    - org.kde.krita
    - org.gimp.GIMP
    - com.ultimaker.cura
    - org.freecadweb.FreeCAD
    - org.torproject.torbrowser-launcher
    - com.mongodb.Compass
  become: yes
