---
- name: Install Snaps Classic
  community.general.snap:
    name: "{{ item }}"
    classic: true
  loop:
    - flutter
    - kubectl
    - kontena-lens
    - helm
    - node
    - sublime-text
    - obsidian
    - intellij-idea
    - datagrip
    - webstorm
    - pycharm
  become: yes

- name: Install Snaps Regular
  community.general.snap:
    name: "{{ item }}"
  loop:
    - postman
    - freecad
    - cura-slicer
    - trello-desktop
    - bitwarden
    - gimp
    - krita
    - spotify
    - discord
    - slack
    - teams
    - brave
  become: yes
