---
- name: Install Snaps Classic
  community.general.snap:
    name: "{{ item }}"
    classic: true
  loop:
    - kontena-lens
    - obsidian
  become: yes

- name: Install Snaps Regular
  community.general.snap:
    name: "{{ item }}"
  loop:
    - postman
    - trello-desktop
    - bitwarden
    - spotify
    - discord
    - slack
    - teams
  become: yes
