---
- name: Configure GDM Wayland Enable
  ansible.builtin.replace:
    path: /etc/gdm3/custom.conf
    regexp: '#WaylandEnable=false'
    replace: 'WaylandEnable=true'
  become: yes
  notify: Restart GDM3

- name: Configure NVIDIA Wayland memory allocation
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/nvidia-power-management.conf
    line: "options nvidia NVreg_PreserveVideoMemoryAllocations=1"
    create: yes
  become: yes
  notify: Restart GDM3
