---
- name: Download Aurora Store
  ansible.builtin.get_url:
    url: "{{ aurora_store_url }}"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/{{ aurora_store_file }}"
    headers:
      User-Agent: Mozilla
  become: no

- name: Download Aurora Droid
  ansible.builtin.get_url:
    url: "{{ aurora_droid_url }}"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/{{ aurora_droid_file }}"
    headers:
      User-Agent: Mozilla
  become: no
