---
- name: Install Waydroid dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
  become: yes

- name: Add Waydroid repository
  ansible.builtin.shell: |
    curl https://repo.waydro.id | bash
  args:
    creates: /etc/apt/sources.list.d/waydroid.list
  become: yes

- name: Install Waydroid
  ansible.builtin.apt:
    name: waydroid
    state: present
  become: yes

- name: Set Waydroid Multi-Windows Prop
  ansible.builtin.command: waydroid prop set persist.waydroid.multi_windows true
  become: yes
  changed_when: false
  ignore_errors: yes

- name: Restart Waydroid Container
  ansible.builtin.systemd:
    name: waydroid-container
    state: restarted
  become: yes
