---
- name: Clone Stable Diffusion WebUI (Linux/Mac)
  ansible.builtin.git:
    repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
    dest: "{{ ansible_env.HOME }}/stable-diffusion-webui"
  when: ansible_os_family != 'Windows' and install_stable_diffusion | bool

- name: Download LM Studio AppImage (Linux)
  ansible.builtin.get_url:
    url: "https://releases.lmstudio.ai/linux/x86_64/standard/latest/LM-Studio-latest-linux-x86_64.AppImage"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/LM-Studio.AppImage"
    mode: '0755'
  when: ansible_system == 'Linux' and install_lm_studio | bool
