#!/usr/bin/env bash
#
# Tier 3: run one scenario end to end inside a systemd-enabled Arch container.
#
# Usage:
#   arch_container.sh <scenario-file>              start, wait, verify, tear down
#   arch_container.sh <scenario-file> --detach     start and return, leaving it running
#   arch_container.sh --collect <run-dir>          verify and tear down a detached run
#
# Each run gets its own container and its own directory under e2e/runs/, holding the
# exact variable file that was used, the full playbook log, the verify log, and a
# result file. Nothing is inferred after the fact.
#
# The playbook always runs detached INSIDE the container, writing its own log and exit
# code there, and this script only watches it. That matters for the long scenarios: a
# full software run takes hours, and tying it to the lifetime of whatever shell started
# it means an ordinary disconnect throws the whole run away. With --detach the container
# keeps working with nothing attached, and --collect finishes the job later from any
# shell.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

require_linux_docker

TIER3_DIR="${E2E_ROOT}/tier3"
IMAGE="installationhelper-e2e-arch:latest"
E2E_USER="lukk"

MODE="wait"
SCENARIO_FILE=""
RUN_DIR=""

case "${1:-}" in
    --collect)
        MODE="collect"
        RUN_DIR="${2:?usage: arch_container.sh --collect <run-dir>}"
        [[ -d "${RUN_DIR}" ]] || { echo "ERROR: no such run directory: ${RUN_DIR}" >&2; exit 2; }
        ;;
    "")
        echo "ERROR: usage: arch_container.sh <scenario-file> [--detach] | --collect <run-dir>" >&2
        exit 2
        ;;
    *)
        SCENARIO_FILE="$1"
        [[ -f "${SCENARIO_FILE}" ]] || { echo "ERROR: no such scenario file: ${SCENARIO_FILE}" >&2; exit 2; }
        [[ "${2:-}" == "--detach" ]] && MODE="detach"
        ;;
esac

# ---------------------------------------------------------------------------
# Start phase
# ---------------------------------------------------------------------------
start_run() {
    # An absent key is normal, not an error. Without the guard, grep's exit 1 travels
    # through pipefail into the assignment and set -e kills the run before it starts.
    scenario_get() {
        grep -E "^${1}:" "${SCENARIO_FILE}" 2>/dev/null \
            | head -1 \
            | sed -E "s/^${1}:[[:space:]]*//; s/[[:space:]]*(#.*)?$//" \
            | tr -d '"' || true
    }

    SCENARIO_NAME="$(scenario_get e2e_scenario_name)"
    SCENARIO_DESC="$(scenario_get e2e_scenario_description)"
    SCENARIO_PROFILE="$(scenario_get e2e_profile)"
    SCENARIO_GENERATE="$(scenario_get e2e_generate)"
    TIMEOUT_MIN="$(scenario_get e2e_timeout_minutes)"
    : "${SCENARIO_NAME:=$(basename "${SCENARIO_FILE}" .yaml)}"
    : "${TIMEOUT_MIN:=180}"

    RUN_ID="$(timestamp)_${SCENARIO_NAME}"
    RUN_DIR="${RUNS_DIR}/${RUN_ID}"
    mkdir -p "${RUN_DIR}"
    CONTAINER="e2e-arch-${SCENARIO_NAME}-$$"
    EFFECTIVE_VARS="${RUN_DIR}/effective-vars.yaml"

    info "Scenario  : ${SCENARIO_NAME}"
    dim  "${SCENARIO_DESC}"
    info "Run dir   : ${RUN_DIR}"
    info "Timeout   : ${TIMEOUT_MIN} minutes"

    # --- effective variable file ---------------------------------------------
    # Order is the whole contract: the scenario's own keys, then any generated
    # software block, then the container limits last so they always win.
    {
        echo "---"
        echo "# Generated by arch_container.sh for scenario ${SCENARIO_NAME}. Do not edit."
        echo "# This is the exact -e input the playbook received."
        grep -vE '^(---|e2e_generate_except:|[[:space:]]*-[[:space:]])' "${SCENARIO_FILE}" | grep -vE '^\s*$' || true
    } > "${EFFECTIVE_VARS}"

    if [[ -n "${SCENARIO_GENERATE}" ]]; then
        # Collected from the two files the wizard itself reads, so a newly added toggle
        # is picked up with no edit here. A hand-maintained copy would quietly stop
        # covering new software, which is the silent gap this suite exists to catch.
        mapfile -t all_toggles < <(
            cat "${ANSIBLE_DIR}/group_vars/all.yaml" "${ANSIBLE_DIR}/group_vars/linux.yaml" \
                | sed -E 's/[[:space:]]+#.*$//; s/[[:space:]]+$//' \
                | grep -E '^install_[a-z0-9_]+: (true|false)$' \
                | sed -E 's/^(install_[a-z0-9_]+):.*/\1/' \
                | sort -u
        )
        mapfile -t excepted < <(sed -n '/^e2e_generate_except:/,/^[a-z]/p' "${SCENARIO_FILE}" \
            | grep -E '^[[:space:]]*-[[:space:]]' | sed -E 's/^[[:space:]]*-[[:space:]]*//' | tr -d '"')

        case "${SCENARIO_GENERATE}" in
            all_software) gen_value="true"  ;;
            no_software)  gen_value="false" ;;
            *) echo "ERROR: unknown e2e_generate value '${SCENARIO_GENERATE}'" >&2; exit 2 ;;
        esac

        echo "# --- generated: e2e_generate=${SCENARIO_GENERATE} ---" >> "${EFFECTIVE_VARS}"
        skipped=()
        for t in "${all_toggles[@]}"; do
            bare="${t#install_}"
            is_excepted=false
            for e in "${excepted[@]+"${excepted[@]}"}"; do
                [[ "${e}" == "${bare}" ]] && is_excepted=true && break
            done
            if [[ "${is_excepted}" == true ]]; then skipped+=("${bare}"); continue; fi
            # A key the scenario states explicitly wins over the generated value.
            grep -qE "^${t}:" "${SCENARIO_FILE}" && continue
            # So does a container limit, appended below. Emitting it here too would
            # produce a duplicate mapping key and a warning per toggle.
            grep -qE "^${t}:" "${TIER3_DIR}/container_limits.yaml" && continue
            echo "${t}: ${gen_value}" >> "${EFFECTIVE_VARS}"
        done
        dim "generated ${#all_toggles[@]} install_ toggles as ${gen_value}"
        [[ ${#skipped[@]} -gt 0 ]] && warn "excluded from the generated set: ${skipped[*]}"
    fi

    echo "# --- container limits (always applied last) ---" >> "${EFFECTIVE_VARS}"
    grep -vE '^(---|#)' "${TIER3_DIR}/container_limits.yaml" | { grep -vE '^\s*$' || true; } >> "${EFFECTIVE_VARS}"

    warn "suppressed as impossible in a container, so NOT covered by this run:"
    grep -E '^[a-z_]+: false$' "${TIER3_DIR}/container_limits.yaml" | sed 's/^/       /' || true

    # --- container ------------------------------------------------------------
    info "Building the base image (cached after the first run)"
    docker build -q -f "${TIER3_DIR}/arch.Dockerfile" -t "${IMAGE}" "${TIER3_DIR}" >/dev/null

    info "Starting the container with systemd as PID 1"
    docker run -d --name "${CONTAINER}" \
        --privileged \
        --cgroupns=host \
        -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
        --tmpfs /run --tmpfs /run/lock \
        "${IMAGE}" >/dev/null

    # Poll rather than sleep blindly, and accept `degraded`: getty and firstboot always
    # fail in a container and neither matters here.
    local state=""
    for _ in $(seq 1 30); do
        state="$(docker exec "${CONTAINER}" systemctl is-system-running 2>/dev/null || true)"
        [[ "${state}" == running || "${state}" == degraded ]] && break
        sleep 1
    done
    info "systemd state: ${state:-unknown}"
    if [[ "${state}" != running && "${state}" != degraded ]]; then
        docker rm -f "${CONTAINER}" &>/dev/null || true
        echo "systemd never came up, aborting" | tee "${RUN_DIR}/result.txt"
        exit 1
    fi

    # Copied in, not bind-mounted. A run must never be able to modify the working tree
    # it is testing.
    info "Copying setup/ into the container"
    docker cp "${REPO_ROOT}/setup" "${CONTAINER}:/work-setup" >/dev/null
    docker exec "${CONTAINER}" bash -c "mkdir -p /work && mv /work-setup /work/setup && chown -R ${E2E_USER}:${E2E_USER} /work"
    docker cp "${EFFECTIVE_VARS}" "${CONTAINER}:/work/effective-vars.yaml" >/dev/null
    docker cp "${TIER3_DIR}/verify.yaml" "${CONTAINER}:/work/verify.yaml" >/dev/null
    docker exec "${CONTAINER}" chown "${E2E_USER}:${E2E_USER}" /work/effective-vars.yaml /work/verify.yaml

    info "Installing Ansible collections"
    docker exec -u "${E2E_USER}" -w /work/setup/ansible "${CONTAINER}" \
        ansible-galaxy collection install -r requirements.yaml >"${RUN_DIR}/galaxy.log" 2>&1 \
        || warn "collection install failed, see ${RUN_DIR}/galaxy.log"

    # --- launch, detached inside the container --------------------------------
    local profile_arg=""
    [[ -n "${SCENARIO_PROFILE}" ]] && profile_arg="-e @profiles/${SCENARIO_PROFILE}.yaml"

    info "Launching the playbook inside the container"
    dim "ansible-playbook site.yaml -i localhost, -c local ${profile_arg} -e @/work/effective-vars.yaml"
    docker exec -d -u "${E2E_USER}" -w /work/setup/ansible \
        -e ANSIBLE_FORCE_COLOR=0 \
        "${CONTAINER}" bash -c "ansible-playbook site.yaml -i 'localhost,' -c local ${profile_arg} -e @/work/effective-vars.yaml > /work/playbook.log 2>&1; echo \$? > /work/playbook.rc"

    # Everything --collect needs, so it does not have to re-derive any of it.
    cat > "${RUN_DIR}/meta.env" <<EOF
CONTAINER=${CONTAINER}
SCENARIO_NAME=${SCENARIO_NAME}
SCENARIO_DESC=${SCENARIO_DESC}
TIMEOUT_MIN=${TIMEOUT_MIN}
RUN_ID=${RUN_ID}
STARTED_AT=$(timestamp)
EOF
}

# ---------------------------------------------------------------------------
# Wait, verify, collect
# ---------------------------------------------------------------------------
wait_for_playbook() {
    local deadline=$(( $(date +%s) + TIMEOUT_MIN * 60 ))
    info "Waiting for the playbook (timeout ${TIMEOUT_MIN} minutes)"
    while true; do
        if docker exec "${CONTAINER}" test -f /work/playbook.rc 2>/dev/null; then
            return 0
        fi
        if ! docker inspect -f '{{.State.Running}}' "${CONTAINER}" 2>/dev/null | grep -q true; then
            warn "the container stopped before the playbook finished"
            return 1
        fi
        if [[ $(date +%s) -gt ${deadline} ]]; then
            warn "the playbook hit the ${TIMEOUT_MIN} minute timeout"
            return 1
        fi
        sleep 15
    done
}

collect_and_verify() {
    PLAYBOOK_LOG="${RUN_DIR}/playbook.log"
    VERIFY_LOG="${RUN_DIR}/verify.log"
    RESULT_FILE="${RUN_DIR}/result.txt"

    docker cp "${CONTAINER}:/work/playbook.log" "${PLAYBOOK_LOG}" &>/dev/null || echo "(no playbook log)" > "${PLAYBOOK_LOG}"
    PLAYBOOK_RC="$(docker exec "${CONTAINER}" cat /work/playbook.rc 2>/dev/null || echo "timeout-or-killed")"
    info "Playbook exit code: ${PLAYBOOK_RC}"

    # Runs regardless of the playbook's exit code. A failed run still has state worth
    # asserting on, and knowing which parts survived is how a failure gets triaged.
    info "Running verification"
    set +e
    docker exec -u "${E2E_USER}" -w /work/setup/ansible \
        -e ANSIBLE_FORCE_COLOR=0 \
        "${CONTAINER}" ansible-playbook /work/verify.yaml -i "localhost," -c local \
        -e "@/work/effective-vars.yaml" >"${VERIFY_LOG}" 2>&1
    VERIFY_RC=$?
    set -e
    info "Verify exit code: ${VERIFY_RC}"

    {
        echo "scenario:      ${SCENARIO_NAME}"
        echo "description:   ${SCENARIO_DESC}"
        echo "run_id:        ${RUN_ID}"
        echo "playbook_rc:   ${PLAYBOOK_RC}"
        echo "verify_rc:     ${VERIFY_RC}"
        echo "playbook_recap:"
        local recap errs
        recap="$(grep -E '^localhost[[:space:]]+:' "${PLAYBOOK_LOG}" || true)"
        [[ -n "${recap}" ]] && sed 's/^/  /' <<<"${recap}" || echo "  (no recap line, the run did not reach the end)"
        echo "errors_and_failures:"
        # Reported as "none found" rather than "none", because a parse error aborts
        # before any task runs and a bare "none" next to a non-zero exit reads as a pass.
        errs="$(grep -E '^(fatal:|failed:|\[ERROR\])' "${PLAYBOOK_LOG}" | head -40 || true)"
        [[ -n "${errs}" ]] && sed 's/^/  /' <<<"${errs}" || echo "  none found in the log, check the log directly"
        echo "verify_assertions:"
        grep -E '^(PASS|FAIL)|assertion' "${VERIFY_LOG}" | head -20 | sed 's/^/  /' || echo "  (none parsed)"
    } > "${RESULT_FILE}"

    cat "${RESULT_FILE}"

    if [[ "${PLAYBOOK_RC}" == "0" ]]; then
        pass "${SCENARIO_NAME}: playbook completed"
    else
        fail "${SCENARIO_NAME}: playbook exited ${PLAYBOOK_RC}" "see ${PLAYBOOK_LOG}"
    fi
    if [[ ${VERIFY_RC} -eq 0 ]]; then
        pass "${SCENARIO_NAME}: verification passed"
    else
        fail "${SCENARIO_NAME}: verification failed" "see ${VERIFY_LOG}"
    fi
}

teardown() {
    docker rm -f "${CONTAINER}" &>/dev/null || true
}

# ---------------------------------------------------------------------------
case "${MODE}" in
    detach)
        start_run
        echo
        info "Detached. The container keeps running with nothing attached to it."
        info "Collect the result with:"
        echo "  ./e2e/tier3/arch_container.sh --collect ${RUN_DIR}"
        info "Watch progress with:"
        echo "  docker exec ${CONTAINER} tail -f /work/playbook.log"
        exit 0
        ;;
    wait)
        start_run
        wait_for_playbook || true
        collect_and_verify
        teardown
        finish "tier 3 / ${SCENARIO_NAME}"
        ;;
    collect)
        # shellcheck disable=SC1091
        source "${RUN_DIR}/meta.env"
        info "Collecting ${SCENARIO_NAME} from ${CONTAINER}"
        if ! docker inspect "${CONTAINER}" &>/dev/null; then
            echo "ERROR: container ${CONTAINER} no longer exists, nothing to collect" >&2
            exit 2
        fi
        if ! docker exec "${CONTAINER}" test -f /work/playbook.rc 2>/dev/null; then
            warn "the playbook is still running. Current task:"
            docker exec "${CONTAINER}" bash -c "grep -E '^\[[0-9:]+\] TASK' /work/playbook.log | tail -1" 2>/dev/null || true
            info "Rerun --collect when it has finished, or watch it with:"
            echo "  docker exec ${CONTAINER} tail -f /work/playbook.log"
            exit 3
        fi
        collect_and_verify
        teardown
        finish "tier 3 / ${SCENARIO_NAME}"
        ;;
esac
