---
- name: Include Unix Environment Variables tasks
  ansible.builtin.include_tasks: env_unix.yaml
  when: ansible_facts['os_family'] != 'Windows'

- name: Include Windows Environment Variables tasks
  ansible.builtin.include_tasks: env_windows.yaml
  when: ansible_facts['os_family'] == 'Windows'
