---
- name: Install Winget packages
  community.windows.win_winget:
    name: "{{ item.value.package }}"
    state: present
  loop: "{{ software_mapping | dict2items }}"
  when:
    - item.value.manager == 'winget'
    - vars[item.key] | default(false) | bool
