---
- name: Include Chocolatey installation tasks
  ansible.builtin.include_tasks: windows_chocolatey.yaml
  when: ansible_facts['os_family'] == 'Windows'

- name: Include Winget installation tasks
  ansible.builtin.include_tasks: windows_winget.yaml
  when: ansible_facts['os_family'] == 'Windows'

