---
- name: Include Android SDK Unix tasks
  ansible.builtin.include_tasks: android_sdk_unix.yaml
  when: ansible_facts['os_family'] != 'Windows' and install_android_sdk | default(false) | bool

- name: Include Android SDK Windows tasks
  ansible.builtin.include_tasks: android_sdk_windows.yaml
  when: ansible_facts['os_family'] == 'Windows' and install_android_sdk | default(false) | bool

