---
- name: Include FVM Unix tasks
  ansible.builtin.include_tasks: fvm_unix.yaml
  when: ansible_facts['os_family'] != 'Windows' and install_flutter | default(false) | bool

- name: Include FVM Windows tasks
  ansible.builtin.include_tasks: fvm_windows.yaml
  when: ansible_facts['os_family'] == 'Windows' and install_flutter | default(false) | bool
