---
- name: Include NVM Unix tasks
  ansible.builtin.include_tasks: nvm_unix.yaml
  when: ansible_facts['os_family'] != 'Windows' and install_nodejs | default(false) | bool

- name: Include NVM Windows tasks
  ansible.builtin.include_tasks: nvm_windows.yaml
  when: ansible_facts['os_family'] == 'Windows' and install_nodejs | default(false) | bool

