---
- name: Install Pyenv build dependencies (Debian)
  become: yes
  ansible.builtin.apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
      - curl
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Pyenv build dependencies (Fedora)
  become: yes
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - zlib-devel
      - bzip2-devel
      - readline-devel
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - curl
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Pyenv build dependencies (Arch)
  become: yes
  community.general.pacman:
    name:
      - base-devel
      - openssl
      - zlib
      - xz
      - tk
      - curl
    state: present
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Install Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    curl https://pyenv.run | bash
  args:
    creates: "{{ non_root_home }}/.pyenv/bin/pyenv"
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"

- name: Install all Python versions via Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    export PYENV_ROOT="{{ non_root_home }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv install --skip-existing {{ item }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  loop:
    - "{{ python310_id }}"
    - "{{ python311_id }}"
    - "{{ python312_id }}"
    - "{{ python313_id }}"
  register: pyenv_install
  changed_when: "'already installed' not in pyenv_install.stderr and 'already exists' not in pyenv_install.stderr"
  failed_when: pyenv_install.rc != 0 and 'already exists' not in pyenv_install.stderr

- name: Set default Python via Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    export PYENV_ROOT="{{ non_root_home }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv global {{ default_python }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  changed_when: true

