---
- name: Include Pyenv Unix tasks
  ansible.builtin.include_tasks: pyenv_unix.yaml
  when: ih_family != 'Windows' and install_python | default(false) | bool

- name: Include Pyenv Windows tasks
  ansible.builtin.include_tasks: pyenv_windows.yaml
  when: ih_family == 'Windows' and install_python | default(false) | bool

