---
- name: Install Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    curl https://pyenv.run | bash
  args:
    creates: "{{ non_root_home }}/.pyenv/bin/pyenv"
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"

- name: Install all Python versions via Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    export PYENV_ROOT="{{ non_root_home }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv install --skip-existing {{ item }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  loop:
    - "{{ python310_id }}"
    - "{{ python311_id }}"
    - "{{ python312_id }}"
    - "{{ python313_id }}"
  register: pyenv_install
  changed_when: "'already installed' not in pyenv_install.stderr and 'already exists' not in pyenv_install.stderr"
  failed_when: pyenv_install.rc != 0 and 'already exists' not in pyenv_install.stderr

- name: Set default Python via Pyenv (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    export PYENV_ROOT="{{ non_root_home }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv global {{ default_python }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  changed_when: true

