---
- name: Install SDKMAN (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    curl -s "https://get.sdkman.io" | bash
  args:
    creates: "{{ non_root_home }}/.sdkman/bin/sdkman-init.sh"
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"

- name: Install all Java Temurin versions via SDKMAN (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    source {{ non_root_home }}/.sdkman/bin/sdkman-init.sh && echo "n" | sdk install java {{ item }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  loop:
    - "{{ java11_id }}"
    - "{{ java17_id }}"
    - "{{ java21_id }}"
    - "{{ java25_id }}"
  register: sdk_java_install
  changed_when: "'is already installed' not in sdk_java_install.stdout"
  failed_when: >
    sdk_java_install.rc != 0 and
    'is already installed' not in sdk_java_install.stdout and
    'is already installed' not in sdk_java_install.stderr

- name: Set default Java via SDKMAN (Linux/Mac)
  ansible.builtin.shell: |
    set -o pipefail
    source {{ non_root_home }}/.sdkman/bin/sdkman-init.sh && sdk default java {{ default_java }}
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ non_root_user }}"
  register: sdk_java_default
  changed_when: "'Default java set to' in sdk_java_default.stdout"

