---
- name: Install Karabiner-Elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present
  when: setup_karabiner | bool

- name: Set macOS Finder Defaults
  ansible.builtin.shell: |
    defaults write com.apple.finder AppleShowAllFiles YES
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    killall Finder
  when: setup_finder_defaults | bool

- name: Copy wallpapers directory for macOS
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../wallpapers"
    dest: "/Library/Desktop Pictures/"
  become: yes
  when: set_custom_wallpaper | bool

- name: Set macOS Wallpaper
  ansible.builtin.shell: |
    osascript -e 'tell application "System Events" to tell every desktop to set picture to "/Library/Desktop Pictures/wallpapers/{{ default_wallpaper }}"'
  when: set_custom_wallpaper | bool
  changed_when: false
