name: local-dev

volumes:
  mysql_data:
  mongodb_data:
  postgres_data:

networks:
  local-network:

services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Lukk1234
      MYSQL_DATABASE: test-spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pLukk1234"]
      timeout: 20s
      retries: 10

  mongodb:
    image: mongo:8.0.10
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: articles
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10

  postgres:
    build:
      context: postgresql
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: Lukk1234
      POSTGRES_DB: test-spring
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost" ]
      timeout: 20s
      retries: 10
