---
- name: Create Windows Backgrounds Directory
  ansible.windows.win_file:
    path: "{{ ansible_env.PUBLIC }}\\Pictures\\Backgrounds"
    state: directory
  when: set_custom_wallpaper | bool

- name: Copy wallpapers directory for Windows
  ansible.windows.win_copy:
    src: "{{ playbook_dir }}/../wallpapers/{{ default_wallpaper }}"
    dest: "{{ ansible_env.PUBLIC }}\\Pictures\\Backgrounds\\{{ default_wallpaper }}"
  when: set_custom_wallpaper | bool

- name: Set Windows Wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: Wallpaper
    data: "{{ ansible_env.PUBLIC }}\\Pictures\\Backgrounds\\{{ default_wallpaper }}"
  when: set_custom_wallpaper | bool

- name: Refresh Windows Desktop to apply wallpaper
  ansible.windows.win_shell: |
    RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
  when: set_custom_wallpaper | bool
  changed_when: false

