---
- name: Enable Windows Features
  ansible.windows.win_optional_feature:
    name: "{{ item }}"
    state: present
  loop:
    - VirtualMachinePlatform
    - Microsoft-Windows-Subsystem-Linux
    - HypervisorPlatform
    - NetFx3
    - NetFx4-AdvSrvs
    - NetFx4Extended-ASPNET45
    - Containers-DisposableClientVM
    - Microsoft-Hyper-V
    - ServicesForNFS-ClientOnly
  when: enable_hyperv | bool

