---
vmware_version: "VMware-Player-Full-17.5.0-22583795.x86_64.bundle"
vmware_download_link: "https://download3.vmware.com/software/WKST-PLAYER-1750/{{ vmware_version }}"
minikube_version: "minikube_latest_amd64.deb"
minikube_download_link: "https://storage.googleapis.com/minikube/releases/latest/{{ minikube_version }}"
kind_version: "latest"
kind_download_link: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
