---
- name: Install Exodus Wallet
  ansible.builtin.apt:
    deb: "https://downloads.exodus.com/releases/exodus-linux-x64-25.13.6.deb"
  become: yes

- name: Download Ledger Live AppImage
  ansible.builtin.get_url:
    url: "https://download.live.ledger.com/latest/linux"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/ledger-app.AppImage"
    mode: '0755'
  become: no

- name: Download Trezor Suite AppImage
  ansible.builtin.get_url:
    url: "https://data.trezor.io/suite/releases/desktop/latest/Trezor-Suite-25.4.2-linux-x86_64.AppImage"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/Trezor-Suite-25.4.2-linux-x86_64.AppImage"
    mode: '0755'
  become: no
