---
- name: Ensure temporary installation folder exists
  ansible.builtin.file:
    path: "{{ non_root_home }}/.lukkInstall"
    state: directory
    mode: '0755'
    owner: "{{ non_root_user }}"
    group: "{{ non_root_user }}"
  become: yes

# --- Flatpak: Required for flatpak applications ---
- name: Install flatpak (RedHat/Fedora)
  ansible.builtin.dnf:
    name: flatpak
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install flatpak (Debian/Ubuntu)
  ansible.builtin.apt:
    name: flatpak
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Flathub repository (Linux)
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  become: yes
  when: ansible_facts['system'] == 'Linux'
  ignore_errors: true

- name: Full system upgrade and autoremove (Debian)
  ansible.builtin.apt:
    upgrade: full
    autoremove: yes
  become: yes
  when: ansible_facts['os_family'] == 'Debian'


- name: Full system upgrade (Arch)
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Full system upgrade (Fedora)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install unzip and zip (Arch)
  community.general.pacman:
    name:
      - unzip
      - zip
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Install unzip and zip (Debian)
  ansible.builtin.apt:
    name:
      - unzip
      - zip
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install unzip, zip and patch (Fedora)
  ansible.builtin.dnf:
    name:
      - unzip
      - zip
      - patch
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'
