---
# --- Cross-distro settings ---

- name: Mount /tmp in RAM
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "tmpfs /tmp tmpfs mode=0777 0 0"
    state: present
  become: yes
  when: setup_tmpfs | bool

- name: Setup UTC time RTC (recommended for Linux-only)
  community.general.timezone:
    hwclock: UTC
  become: yes

# --- Locale: Debian ---

- name: Generate PL locale (Debian)
  community.general.locale_gen:
    name: pl_PL.UTF-8
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Set EN locale as default (Debian)
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: "LANG=en_US.UTF-8"
    create: true
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Polish language packs (Ubuntu)
  ansible.builtin.apt:
    name:
      - language-pack-pl
      - language-pack-gnome-pl
      - language-pack-pl-base
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'

- name: Install Polish locale support (Debian)
  ansible.builtin.apt:
    name:
      - locales
      - task-polish
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] != 'Ubuntu'

# --- Locale: Arch ---

- name: Enable pl_PL.UTF-8 locale (Arch)
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    line: "pl_PL.UTF-8 UTF-8"
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Generate locales (Arch)
  community.general.locale_gen:
    name: pl_PL.UTF-8
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Set EN locale as default (Arch)
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: "LANG=en_US.UTF-8"
    create: yes
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

# --- Locale: Fedora ---

- name: Set EN locale as default (Fedora)
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    regexp: '^LANG='
    line: "LANG=en_US.UTF-8"
    create: true
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Polish locale support (Fedora)
  ansible.builtin.dnf:
    name: glibc-langpack-pl
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'
