---
- name: Set Default Apps via xdg-mime
  ansible.builtin.command: "xdg-mime default {{ item.app }} {{ item.mime }}"
  loop:
    - { app: "{{ default_word_app }}", mime: "application/msword" }
    - { app: "{{ default_excel_app }}", mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }
    - { app: "{{ default_presentation_app }}", mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation" }
    - { app: "{{ default_pdf_app }}", mime: "application/pdf" }
    - { app: "{{ default_internetBrowser_app }}", mime: "text/html" }
    - { app: "{{ default_video_app }}", mime: "video/mp4" }
  become: no
  changed_when: false
