---
- name: Install Gnome Tools
  ansible.builtin.apt:
    name:
      - gnome-tweaks
      - gnome-online-accounts
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-manager
      - gnome-shell-extensions
      - chrome-gnome-shell
      - gnome-calendar
    state: present
  become: yes
