---
- name: Copy wallpapers directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../wallpapers"
    dest: "/usr/share/backgrounds/"
  become: yes

- name: Set GNOME themes and backgrounds
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/desktop/interface/color-scheme", value: "'prefer-dark'" }
    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Yaru-dark'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/wallpapers/forest-house.jpg'" }
    - { key: "/org/gnome/desktop/background/picture-uri-dark", value: "'file:///usr/share/backgrounds/wallpapers/forest-house.jpg'" }
    - { key: "/org/gnome/desktop/interface/clock-show-seconds", value: "true" }
    - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true" }
  become: no
