---
# Master Toggles for System Setup
install_system_core: true
setup_gnome: true
setup_zsh: true
install_dev_tools: true
install_virtualization: true
setup_security: true
install_gaming: true
install_other_apps: true
install_waydroid: false
install_crypto_tools: false

# Specific System Core Settings
setup_hibernate: false
setup_tmpfs: true
toggle_wayland_nvidia: false

# Gnome specific apps/settings
default_video_app: vlc_vlc.desktop
default_internetBrowser_app: google-chrome.desktop
default_pdf_app: okular_okular.desktop
default_word_app: onlyoffice-desktopeditors.desktop
default_excel_app: onlyoffice-desktopeditors.desktop
default_presentation_app: onlyoffice-desktopeditors.desktop
favorite_apps: "['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'sublime-text_subl.desktop', 'intellij-idea-ultimate_intellij-idea-ultimate.desktop', 'lens.desktop', 'postman.desktop']"

# Dash to dock specific settings
dash_dock_position: 'LEFT'
dash_dock_disable_ubuntu_dock: false

# Feature Toggles for other specific apps
install_tor: false
install_brave: true

# SDKMan / Java Toggles
install_java: true

# Gaming Toggles
install_wine: false
install_steam: true
install_lutris: false

# Virtualization toggles
install_virtualbox: true
install_vmware: true
install_docker: true
install_minikube: true
install_kind: true
