---
- name: Install Brave Browser repository key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
  become: yes
  when: install_brave | bool

- name: Add Brave Browser repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave-browser-release
  become: yes
  when: install_brave | bool

- name: Install Brave Browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
    update_cache: yes
  become: yes
  when: install_brave | bool

- name: Remove Firefox snap
  community.general.snap:
    name: firefox
    state: absent
  become: yes
  when: install_firefox | bool

- name: Remove Firefox apt
  ansible.builtin.apt:
    name: firefox
    state: absent
  become: yes
  when: install_firefox | bool

- name: Add Mozilla Team PPA
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
  become: yes
  when: install_firefox | bool

- name: Pin Firefox PPA priority
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/mozilla-firefox
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
  become: yes
  when: install_firefox | bool

- name: Allow unattended upgrades for Firefox PPA
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    content: 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";'
  become: yes
  when: install_firefox | bool

- name: Install Firefox from PPA
  ansible.builtin.apt:
    name: firefox
    state: present
    update_cache: yes
  become: yes
  when: install_firefox | bool

- name: Download Tor Browser
  ansible.builtin.get_url:
    url: "{{ tor_browser_url }}"
    dest: "{{ ansible_env.HOME }}/.lukkInstall/{{ tor_browser_file }}"
  become: no
  when: install_tor | bool

- name: Extract Tor Browser
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/.lukkInstall/{{ tor_browser_file }}"
    dest: /opt/
    remote_src: yes
    creates: /opt/tor-browser
  become: yes
  when: install_tor | bool

- name: Set Tor Browser permissions
  ansible.builtin.file:
    path: /opt/tor-browser
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    recurse: yes
  become: yes
  when: install_tor | bool

- name: Register Tor Browser Desktop App
  ansible.builtin.command: ./start-tor-browser.desktop --register-app
  args:
    chdir: /opt/tor-browser/tor-browser_en-US/
  become: no
  when: install_tor | bool
  ignore_errors: yes