---
- name: Install Speedtest CLI
  ansible.builtin.apt:
    name: speedtest-cli
    state: present
  become: yes

- name: Create Speedtest opt directory
  ansible.builtin.file:
    path: /opt/speedtest-cli
    state: directory
    mode: '0755'
  become: yes

- name: Copy Speedtest assets
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "{{ playbook_dir }}/../../icons/speedtest.png", dest: "/opt/speedtest-cli/speedtest.png", mode: '0644' }
    - { src: "{{ playbook_dir }}/../../scripts/speedtest-starter.sh", dest: "/opt/speedtest-cli/speedtest-starter.sh", mode: '0755' }
    - { src: "{{ playbook_dir }}/../../shortcuts/speedtest.desktop", dest: "/usr/share/applications/speedtest.desktop", mode: '0644' }
  become: yes
