---
- name: Download AppImageLauncher
  ansible.builtin.apt:
    deb: "{{ appimage_launcher_url }}"
  become: yes

- name: Download Antigravity
  ansible.builtin.apt:
    deb: "{{ antigravity_url }}"
  become: yes

- name: Download TeamViewer
  ansible.builtin.apt:
    deb: "{{ teamviewer_url }}"
  become: yes

- name: Download VeraCrypt
  ansible.builtin.apt:
    deb: "{{ veracrypt_url }}"
  become: yes
