---
- name: Install KeepassXC
  community.general.snap:
    name: keepassxc
  become: yes

- name: Execute KeepassXC Helper Script
  ansible.builtin.command: "{{ playbook_dir }}/../../config/keepassxc-snap-helper.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json"
  become: no
  ignore_errors: yes
